#!/usr/bin/env bash

function main() {
    local i
    for ((i = 1; i <= $#; i++)); do
        if [[ "${@:$i:1}" == "-N" ]]; then
            local name="${*:$i+1:1}"
        fi
    done

    echo "Your job $$ (\"${name}\") has been submitted"

    local me=$(basename "$0")
    local tmpfile=$(mktemp -t "$me-XXXX.$$")
    echo "${me} $*" > "$tmpfile"
}

main "$@"
